#!/bin/sh
#
# A fuzzy file explorer
#
# Dpendencies:
#              sed, awk, fzf, faint-launch, faint-config,
#              faint-fetch-config, faint-explore, faint-bookmark & faint-operate
#              vidir (Optional)
#
# Usage: faint (explores the current directory)
#        faint DIR (explores specified directory)
#        faint -l (explores the last visited directory)
#        faint -h (shows help)

if [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/faint/config" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/faint/config"
else
  . /usr/share/faint/faint-config
fi

DATA_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/faint"
export FINAL_PATH=$DATA_PATH/FAINT_FINAL
export FILTERS_PATH=$DATA_PATH/FAINT_FILTERS
export BOOKMARKS_PATH=$DATA_PATH/FAINT_BOOKMARKS

export FAINT_PID=$$
export FZF_DEFAULT_OPTS="\
   $FZF_DEFAULT_OPTS
   --reverse --border --no-info --margin 15%,30% --no-color --header ''
   -m --cycle
   --bind \"$KEY_QUIT:cancel\"
   --bind \"$KEY_OPERATE:execute(faint-operate {+})+reload(faint-explore -r)+clear-query+top\"
   --bind \"$KEY_BACK:reload(faint-explore -b)+clear-query+top\"
   --bind \"$KEY_SHELL:abort+execute(kill -35 $$)\"

   --bind \"$KEY_UP:up\"
   --bind \"$KEY_DOWN:down\"
   --bind \"$KEY_REFRESH:reload(faint-explore -r)\"

   --bind \"$KEY_MARK_ALL:toggle-all\"
   --bind \"$KEY_MARK_DOWN:toggle-down\"
   --bind \"$KEY_MARK_UP:toggle-up\"

   --bind \"$KEY_BOOKMARK_BROWSE:execute(faint-bookmark -b)+reload(faint-explore -r)+clear-query+top\"
   --bind \"$KEY_BOOKMARK_ADD:execute(faint-bookmark -a)\"

   --bind \"$KEY_LAUNCH:reload(faint-explore -c {})+clear-query+top\"
   --bind \"$KEY_RUN:execute(faint-explore -l {})\"

   --bind \"$KEY_TOGGLE_FILTERS:reload(faint-explore -t filters)\"
   --bind \"$KEY_TOGGLE_HIDDEN:reload(faint-explore -t hidden)\"

   --bind \"$KEY_DEPTH_PLUS:reload(faint-explore -d plus)\"
   --bind \"$KEY_DEPTH_MINUS:reload(faint-explore -d minus)\"
   --bind \"$KEY_DEPTH_RESET:reload(faint-explore -d reset)\"

   "

export LAST_PATH=/tmp/FAINT_LAST_$$
export MAX_DEPTH_PATH=/tmp/FAINT_MAX_DEPTH_$$
export SHOW_HIDDEN_PATH=/tmp/FAINT_SHOW_HIDDEN_$$
export USE_FILTERS_PATH=/tmp/FAINT_USE_FILTERS_$$

export LAUNCH_FILE_PATH=/tmp/FAINT_FILE_FILE
export FILE_LIST_PATH=/tmp/FAINT_FILE_LIST

help() {
   while IFS= read -r line; do
      echo "$line"
   done << eof
Usage: faint
   or: faint DIR
   or: faint -l
Launch faint on the current directory, on a specified directory or the last visited directory.
eof
   exit
}

cleanup() {
   rm -f \
      $LAST_PATH \
      $MAX_DEPTH_PATH \
      $SHOW_HIDDEN_PATH \
      $USE_FILTERS_PATH \
      $LAUNCH_FILE_PATH \
      $FILE_LIST_PATH
}

make_dir() {
   echo What it is called?
   read -r NAME
   read -r LAST_DIR < "$LAST_PATH"
   mkdir -p "$LAST_DIR/$NAME"
   cd "$LAST_DIR/$NAME"
   : > "$LAST_DIR/$NAME/delete_me_afterwards"
   exec "$0" "$LAST_DIR/$NAME"
}

bulk_move() {
   read -r LAST_DIR < "$LAST_PATH"
   /usr/local/bin/hulk "$LAST_DIR"
   exec "$0" "$LAST_DIR"
}

launch() {
   read -r FILE < "$LAUNCH_FILE_PATH"
   execute "$FILE"
   read -r LAST_DIR < "$LAST_PATH"
   exec "$0" "$LAST_DIR"
}

change_root() {
   read -r LAST_DIR < "$LAST_PATH"
   cd "$LAST_DIR" || exit 1
   exec "$SHELL"
}

init_filters() {
   [ -f "$FILTERS_PATH" ] ||
      faint-fetch-config "$FILTERS" -k |
      awk '{printf "%s\\|",$0;}' |
         sed -e 's/|\./|\\./g' -e 's/\\|$//g' \
            > "$FILTERS_PATH"
}

init_configs() {
   echo "$MAX_DEPTH" > $MAX_DEPTH_PATH
   echo "$SHOW_HIDDEN" > $SHOW_HIDDEN_PATH
   echo "$USE_FILTERS" > $USE_FILTERS_PATH
}

init_paths() {
   echo "$PWD" > "$LAST_PATH"
   [ -d "$DATA_PATH" ] || mkdir -p "$DATA_PATH"
}

process_args() {
   case $1 in
      -l) read -r DEST < "$FINAL_PATH" ;;
      -h) help ;;
      *) DEST=$1 ;;
   esac
}

process_args "$@"
init_paths
init_filters
init_configs

trap 'change_root' RTMIN+1
trap 'launch' RTMIN+2
trap 'bulk_move' RTMIN+3
trap 'make_dir' RTMIN+4
trap 'cleanup' INT TERM QUIT EXIT

faint-explore "${DEST:-$PWD}" | fzf
mv "$LAST_PATH" "$FINAL_PATH"
