#!/bin/sh
#
# Helper script for faint. Allows misc operations on files
#
# Dependencies: fzf, faintrc & faint-fetch-config

. "$HOME"/.local/share/faint/faintrc

export FZF_DEFAULT_OPTS="\
   $FZF_DEFAULT_OPTS
   +m
   --bind \"$KEY_LAUNCH:accept\"
   "

read -r LAST_DIR < "$LAST_PATH"

FILE_ARGS=$(
    for file in "$@"; do
        echo "$LAST_DIR/${file#* }"
    done
)

[ -f "$FILE_LIST_PATH" ] \
    && FILE_LIST=$(
        while read -r file; do
            echo "$file"
        done < "$FILE_LIST_PATH"
    )

CHOICE=$(faint-fetch-config "$OPS" -k | fzf) \
    && CMD=$(faint-fetch-config "$OPS" -v "${CHOICE#* }") \
    && $CMD 2> /dev/null
