#!/bin/sh
#
# Helper script for faint: fetches the relevant configs
#
# Dependency: Milky pure baby!

CURRENT_IFS=$IFS
IFS=$(printf ';')
for line in $1; do
   case $2 in
      -v)
         case $line in
            *"$3"[:\|]*) TEMP=${line%;*} && echo "${TEMP#*:}" && break ;;
         esac
         ;;
      -k) printf "%s" "${line%:*}" ;;
   esac
done
IFS=$CURRENT_IFS
