#!/bin/sh
#
# Helper script for faint; lists file and formats the view
#
# Dependencie: find & faint-config

. faint-config

_get_launch_cmd() {
   CURRENT_IFS=$IFS
   IFS=$(printf ';')
   for line in $LAUNCH_CMD; do
      case $line in
         *"$1"*) TEMP=${line%;*} && echo "${TEMP#*:}" && break ;;
      esac
   done
   IFS=$CURRENT_IFS
}

faint_launch() {
   MIME=$(file --mime-type "$1" -bL)
   CMD=$(_get_launch_cmd "$MIME")
   [ -z "$CMD" ] &&
      notify-send -t 0 "No command found for $MIME type" &&
      CMD=$(_get_launch_cmd default)
   "$CMD" "$1" 2> /dev/null
}

_get_icon() {
   CURRENT_IFS=$IFS
   IFS=$(printf ';')
   for line in $ICONS; do
      case $line in
         *"$1"*) TEMP=${line%;*} && echo "${TEMP#*:}" && break ;;
      esac
   done
   IFS=$CURRENT_IFS
}

format() {
   while read -r file; do
      [ "$file" = . ] && continue
      if [ -d "$file" ]; then
         PREFIX=$(_get_icon dir)
      else
         ICON=$(_get_icon "${file##*.}")
         if [ -n "$ICON" ]; then
            PREFIX=$ICON
         else
            PREFIX=$(_get_icon file)
         fi
      fi
      echo "$PREFIX ${file#./}"
   done
}

list() {
   echo "$PWD" > "$LAST_PATH"
   read -r DEPTH < "$DEPTH_PATH"
   read -r FILTERS < "$FILTERS_PATH"
   find . -maxdepth "$DEPTH" \
      ! -regex ".*\($FILTERS\).*" \
      2> /dev/null
}

process_args() {
   read -r LAST_DIR < "$LAST_PATH"
   case $1 in
      -b)
         cd "${LAST_DIR%/*}" || exit 1
         ;;
      -e) shift && cd "$1" || exit 1 ;;
      -l)
         shift
         NEW_DIR=${1#* }
         DEST=$LAST_DIR/$NEW_DIR
         if ! cd "$DEST"; then
            faint_launch "$DEST"
            cd "$LAST_DIR" || exit 1
         fi
         ;;
   esac
}

main() {
   process_args "$@"
   list | format
}
main "$@"
