#!/bin/sh
#
# Helper script for faint. Allows misc operations on files
#
# Dependencies: fzf, faint-config & faint-fetch-config

. faint-config

FILE_LIST_PATH=/tmp/FAINT_FILE_LIST

read -r LAST_DIR < "$LAST_PATH"

export FZF_DEFAULT_OPTS="\
   $FZF_DEFAULT_OPTS
   +m
   --bind \"$KEY_LAUNCH:accept\"
   "

FILE_ARGS=$(
   for file in "$@"; do
      echo "$LAST_DIR/${file#* }"
   done
)

[ -f "$FILE_LIST_PATH" ] && read -r FILE_LIST < "$FILE_LIST_PATH"

CHOICE=$(faint-fetch-config "$OPS" -k | fzf) &&
   CMD=$(faint-fetch-config "$OPS" -v "${CHOICE#* }") &&
   $CMD 2> /dev/null
