#!/bin/sh
#
# A fuzzy file explorer
#
# Dpendencies:
#    sed, awk, fzf, faint-config, faint-list, faint-operate & faint-fetch-config
#
# Usage: faint (launch on the current directory)
#        faint -l (launch on the last visited directory)
#        faint -d 3 (explore directories with specified depth)
#        faint <PATH> (explore certain directories)
#        faint -n (explore without filtering)
#        faint -d 3 -n (flag overloading is possible)

. faint-config

export DEPTH_PATH=/tmp/FAINT_DEPTH
export LAST_PATH=/tmp/FAINT_LAST_$$
export FINAL_PATH=/tmp/FAINT_FINAL
export FILTERS_PATH=~/.local/share/faint/FAINT_FILTERS

FZF_DEFAULT_OPTS="\
   $FZF_DEFAULT_OPTS
   --reverse --border --no-info --margin 15%,30% --no-color --header ''
   -m --cycle
   --bind \"$KEY_LAUNCH:reload(faint-list -l {})+clear-query\"
   --bind \"$KEY_OPERATE:abort+execute(faint-operate {+})+execute(faint -l)\"
   --bind \"$KEY_BACK:reload(faint-list -b)+clear-query\"
   --bind \"$KEY_QUIT:cancel\"
   --bind \"$KEY_SHELL:execute(kill -35 $$)+abort\"
   --bind \"$KEY_UP:up\"
   --bind \"$KEY_DOWN:down\"
   --bind \"$KEY_MARK_ALL:toggle-all\"
   "
export FZF_DEFAULT_OPT

FILTERING=1

set_filters() {
   if [ "$FILTERING" = 0 ]; then
      echo zzz > "$FILTERS_PATH"
   else
      faint-fetch-config "$FILTERS" -k |
         awk '{printf "%s\\|",$0;}' |
         sed -e 's/|\./|\\./g' -e 's/\\|$//g' \
            > "$FILTERS_PATH"
   fi
}

change_root() {
   read -r LAST_DIR < "$LAST_PATH"
   cd "$LAST_DIR" || exit 1
   $SHELL
}

init() {
   echo "$PWD" > "$LAST_PATH"
   echo "${DEPTH:-1}" > $DEPTH_PATH
   [ -d ~/.local/share/faint ] || mkdir -p ~/.local/share/faint
   set_filters
}

process_args() {
   while :; do
      case $1 in
         -d) shift && DEPTH=$1 ;;
         -l) read -r DEST < $FINAL_PATH ;;
         -n) FILTERING=0 ;;
         *) break ;;
      esac
      shift
   done
   [ "$1" ] && DEST=$1
}

main() {
   process_args "$@"
   init
   trap 'change_root' RTMIN+1
   faint-list -e "${DEST:-$PWD}" | fzf
   mv "$LAST_PATH" "$FINAL_PATH"
}
main "$@"
