#!/bin/sh
#
# Helper script for faint. Allows misc operations on files
#
# Dependencie: cat

#===============================================================================
#                             Config
#===============================================================================

trash() { notify-send trashing; }
delete() { rm -fr "$FILES"; }
yank() { echo "$FILES" | xsel -b && echo "$FILES" > "$LIST"; }
paste() { rsync -a "$(cat "$LIST")" .; }
duplicate() { rsync -a "$FILES" "$FILES~"; }
move() { mv "$(cat "$LIST")" .; }
link_soft() { cp -frus "$(cat "$LIST")" .; }
link_hard() { cp -frul "$(cat "$LIST")" .; }

OPS="\
⚔ Trash:trash;
❌ Delete:delete;
© Yank:yank;
🖌 Paste:paste;
🚚 Move:move;
‼ Duplicate:duplicate;
🗞 Soft Link:link_soft;
🌴 Hard Link:link_hard;
"

#===============================================================================
#                             Script
#===============================================================================

LIST=/tmp/list
FILES=$(
   for file in "$@"; do
      # readlink -f "${file#* }"
      echo "$(cat "$LAST_PATH")/${file#* }"
   done
)
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --bind=tab:down,btab:up,\;:accept"

get_config() {
   CURRENT_IFS=$IFS
   IFS=$(printf ';')
   for line in $OPS; do
      case $1 in
         -o) printf "%s" "${line%%:*}" ;;
         -c)
            case $line in
               *"$2"*) TEMP=${line%;*} && echo "${TEMP#*:}" && break ;;
            esac
            ;;
      esac
   done
   IFS=$CURRENT_IFS
}

main() {
   CHOICE=$(get_config -o | fzf) &&
      CMD=$(get_config -c "${CHOICE#* }") &&
      $CMD 2> /dev/null
}
main
