#!/bin/sh
#
# Config file for faint
# Dependencies: pkill

#===============================================================================
#                             Default Settings
#===============================================================================

SHOW_HIDDEN=1
USE_FILTERS=1
MAX_DEPTH=1

#===============================================================================
# Bindings ( ⁉ has to be a single character!) [ More on fzf man page ]
#===============================================================================

KEY_LAUNCH=';'
KEY_BACK=','
KEY_OPERATE='space'
KEY_QUIT='esc'

KEY_SHELL='enter'

KEY_UP='btab'
KEY_DOWN='tab'

KEY_MARK_DOWN=']'
KEY_MARK_UP='['
KEY_MARK_ALL='\\'

KEY_BOOKMARK_BROWSE="'"
KEY_BOOKMARK_ADD='\"'

KEY_TOGGLE_HIDDEN="."
KEY_TOGGLE_FILTERS='>'

KEY_REFRESH="<"

KEY_DEPTH_PLUS="="
KEY_DEPTH_MINUS="-"
KEY_DEPTH_RESET="_"

#===============================================================================
#                             Filters
#===============================================================================

#---------------------------------------
# <FILE>/<FOLDER;
#---------------------------------------
FILTERS="\
node_modules;
package-lock.json;
yarn.lock;
.git;
"

#===============================================================================
#                             Operations
#===============================================================================

# Variable Conventions
#     FILE_ARGS      = Files selected for operation ( ⁉ Has to be quoted )
#     FILE_LIST      = Files tracked for consecutive operations
#     FILE_LIST_PATH = PATH for tracking files
#     LAST_DIR       = Current path

#---------------------------------------
# Operation Functions
#---------------------------------------
delete() { echo "$FILE_ARGS" | while read -r file; do rm -fr "$file"; done; }
trash() { echo "$FILE_ARGS" | while read -r file; do mv "$file" "$TRASH"; done; }
paste() {
   echo "$FILE_LIST" |
      while read -r file; do
         cp -br "$file" "$LAST_DIR"
      done
}
move() {
   echo "$FILE_LIST" |
      while read -r file; do
         mv "$file" "$LAST_DIR"
      done
}
link_soft() {
   echo "$FILE_LIST" |
      while read -r file; do
         cp -frs "$file" "$LAST_DIR"
      done
}
link_hard() {
   echo "$FILE_LIST" |
      while read -r file; do
         cp -frl "$file" "$LAST_DIR"
      done
}
own() {
   echo "$FILE_ARGS" |
      while read -r file; do
         sudo -n chown -R "$USER" "$file"
      done
}
yank() {
   echo "$FILE_ARGS" | xsel -b
   echo "$FILE_ARGS" > "$FILE_LIST_PATH"
}
rename_bulk() {
   kill -37 "$FAINT_PID"
   pkill -P "$FAINT_PID"
}

#---------------------------------------
# <OPERATION_NAME>:<OPERATION_FUNCTION>;
#---------------------------------------
OPS="\
⚔  Trash:trash;
❌ Delete:delete;
©  Yank:yank;
🖌  Paste:paste;
🚚 Move:move;
🗞  Soft Link:link_soft;
🌴 Hard Link:link_hard;
😎 Own:own;
🏷  Bulk Rename:rename_bulk;
"

#===============================================================================
#                             Launching
#===============================================================================

execute() {
   case ${1##*.} in
      # <EXT1> | <EXT2 | ...) <CMD>;;
      mp4 | mkv | gif) mpv "$1" ;;
      # default
      *) $EDITOR "$1" ;;
   esac
}

#===============================================================================
#                               Icons
#===============================================================================

#---------------------------------------
# <EXT_1|EXT_2|...>:<ICON>;
#---------------------------------------
ICONS="\
dir:📁;
file:📃;
link:⛓;
iso|img:📀;
png|ico:🖼;
jpg|jpeg:📸;
part:💔;
json:📒;
md:📘;
tex:📜;
css|sass|scss:🎨;
html|pug|url:🌎;
pdf|epub:📚;
mp4|mkv:🎥;
"
