#!/bin/sh
#
# Config file for faint

#===============================================================================
# Bindings ( ⁉ has to be a single character!) [ More on fzf man page ]
#===============================================================================

KEY_LAUNCH=';'
KEY_BACK=','
KEY_OPERATE='space'
KEY_QUIT='esc'

KEY_SHELL='enter'
KEY_EDIT="'"

KEY_UP='['
KEY_DOWN=']'

KEY_MARK_DOWN='tab'
KEY_MARK_UP='btab'
KEY_MARK_ALL='\\'

KEY_REFRESH="."
KEY_BOOKMARK="/"

#===============================================================================
#                             Filters
#===============================================================================

#---------------------------------------
# <FILE>/<FOLDER;
#---------------------------------------
FILTERS="\
node_modules;
package-lock.json;
yarn.lock;
.git;
"

#===============================================================================
#                             Operations
#===============================================================================

# Variable Conventions
#     FILE_ARGS      = Files selected for operation ( ⁉ Has to be unquoted )
#     FILE_LIST      = Files tracked for consecutive operations
#     FILE_LIST_PATH = PATH for tracking files
#     LAST_DIR       = Current path

#---------------------------------------
# Operation Functions
#---------------------------------------
delete() { rm -fr $FILE_ARGS; }
trash() { mv $FILE_ARGS "$TRASH"; }
yank() { echo $FILE_ARGS | xsel -b && echo $FILE_ARGS > "$FILE_LIST_PATH"; }
paste() { cp -br $FILE_LIST "$LAST_DIR"; }
move() { mv $FILE_LIST "$LAST_DIR"; }
link_soft() { cp -frs $FILE_LIST "$LAST_DIR"; }
link_hard() { cp -frl $FILE_LIST "$LAST_DIR"; }

#---------------------------------------
# <OPERATION_NAME>:<OPERATION_FUNCTION>;
#---------------------------------------
OPS="\
⚔ Trash:trash;
❌ Delete:delete;
© Yank:yank;
🖌 Paste:paste;
🚚 Move:move;
🗞 Soft Link:link_soft;
🌴 Hard Link:link_hard;
"

#===============================================================================
#                             Launching
#===============================================================================

#---------------------------------------
# Launch Functions
#---------------------------------------

# Use "$1" for referencing the file
edit() {
   tmux split-window -h "$EDITOR $1" \; \
      swap-pane -d -t :.1 \; \
      select-layout main-vertical
}

#-------------------------------------------------------
# <EXT_1|EXT_2>:<Launch_CMD/Launch_FUNCTION>;
#-------------------------------------------------------
LAUNCH_CMDS="\
mp4|mkv:mpv;
default:edit;
"

#===============================================================================
#                               Icons
#===============================================================================

#---------------------------------------
# <EXT_1|EXT_2|...>:<ICON>;
#---------------------------------------
ICONS="\
dir:📁;
file:📃;
link:⛓;
iso|img:📀;
png|ico:🖼;
jpg|jpeg:📸;
part:💔;
json:📒;
md:📘;
tex:📜;
css|sass|scss:🎨;
html|pug:🌎;
pdf|epub:📚;
mp4|mkv:🎥;
"

#===============================================================================
#                             Favorites
#===============================================================================

#---------------------------------------
# <TITLE>:<PATH>;
#---------------------------------------
BOOKMARKS="\
Git:/mnt/horcrux/git/own;
Downloads:/mnt/horcrux/downloads;
Torrents:/mnt/horcrux/torrents;
Notes:/mnt/horcrux/notes;
"
