#!/bin/sh
#
# Helper script for faint; lists file and formats the view
#
# Dependencie: find, faint-config & faint-fetch-config

. faint-config

faint_launch() {
   EXT=${1##*.}
   CMD=$(faint-fetch-config "$LAUNCH_CMDS" -v "$EXT")
   [ -z "$CMD" ] && CMD=$(faint-fetch-config "$LAUNCH_CMDS" -v default)
   "$CMD" "$1" > /dev/null 2>&1 &
}

format() {
   while read -r file; do
      [ "$file" = . ] && continue
      if [ -d "$file" ]; then
         PREFIX=$(faint-fetch-config "$ICONS" -v dir)
      else
         ICON=$(faint-fetch-config "$ICONS" -v "${file##*.}")
         if [ -n "$ICON" ]; then
            PREFIX=$ICON
         else
            PREFIX=$(faint-fetch-config "$ICONS" -v file)
         fi
      fi
      echo "$PREFIX ${file#./}"
   done
}

list() {
   echo "$PWD" > "$LAST_PATH"
   read -r DEPTH < "$DEPTH_PATH"
   read -r FILTERS < "$FILTERS_PATH"
   find . -maxdepth "$DEPTH" \
      ! -regex ".*\($FILTERS\).*" \
      2> /dev/null
}

process_args() {
   read -r LAST_DIR < "$LAST_PATH"
   case $1 in
      -b)
         cd "${LAST_DIR%/*}" || exit 1
         ;;
      -e) shift && cd "$1" || exit 1 ;;
      -l)
         shift
         NEW_DIR=${1#* }
         DEST=$LAST_DIR/$NEW_DIR
         if ! cd "$DEST"; then
            faint_launch "$DEST"
            cd "$LAST_DIR" || exit 1
         fi
         ;;
   esac
}

main() {
   process_args "$@"
   list | format
}
main "$@"
