#!/bin/sh
#
# Helper script for faint; lists file and formats the view
#
# Dependencie: find & faint-config

. faint-config

list() {
   echo "$PWD" > "$LAST_PATH"
   read -r DEPTH < "$DEPTH_PATH"
   read -r FILTERS < "$FILTERS_PATH"
   find . -maxdepth "$DEPTH" \
      ! -regex ".*\($FILTERS\).*" \
      2> /dev/null
}

process_args() {
   read -r LAST_DIR < "$LAST_PATH"
   while :; do
      case $1 in
         -b)
            cd "${LAST_DIR%/*}" || exit 1
            ;;
         -e) shift && cd "$1" || exit 1 ;;
         -l)
            shift
            NEW_DIR=${1#* }
            DEST=$LAST_DIR/$NEW_DIR
            if ! cd "$DEST"; then
               faint_launch "$DEST"
               cd "$LAST_DIR" || exit 1
            fi
            ;;
         *) break ;;
      esac
      shift
   done
}

main() {
   process_args "$@"
   list | format
}
main "$@"
